# YAML
manager: nrhevm.itmlabs.local
Hosts:
  remote:
    - nhost3.itmlabs.local
database: engine
userDatabase: NDg1ZjIzNGZAWlc1bmFXNWw=
passDatabase: MjUzYTI3NWVAV25aUVZEQnJaRVJDT0hGVllWZDBVbTVaWTIxNk13PT0=
table: storage_server_connections
mpath:
  iscsiportalA:
    - 192.168.113.254
    - 192.168.113.254
  iscsiportalB:
    - 192.168.113.254
    - 192.168.113.254
luns:
  lunIDB:
    - iqn.2015-12.local.itmlabs:lun01a
    - iqn.2015-12.local.itmlabs:lun02a
  lunIDA:
    - iqn.2015-12.local.itmlabs:lun01adrp
    - iqn.2015-12.local.itmlabs:lun02adrp